# Generated by Django 6.0.4 on 2026-04-30 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('labeling', 'Data Labeling'), ('transcription', 'Transcription'), ('verification', 'Verification'), ('review', 'Dataset Review'), ('annotation', 'Annotation')], max_length=50)),
                ('data_type', models.CharField(choices=[('image', 'Image'), ('text', 'Text'), ('audio', 'Audio'), ('video', 'Video'), ('tabular', 'Tabular')], max_length=50)),
                ('job_type', models.CharField(choices=[('fixed', 'Fixed Price'), ('hourly', 'Hourly')], default='fixed', max_length=20)),
                ('experience', models.CharField(choices=[('entry', 'Entry Level'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], default='entry', max_length=20)),
                ('project_length', models.CharField(choices=[('less_1_week', 'Less than 1 week'), ('1_4_weeks', '1 to 4 weeks'), ('1_3_months', '1 to 3 months'), ('3_plus_months', '3+ months')], default='1_4_weeks', max_length=20)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hours_per_week', models.IntegerField(blank=True, null=True)),
                ('skills', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('allow_multiple', models.BooleanField(default=False)),
                ('require_verification', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_tasks', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='users.task')),
            ],
            options={
                'unique_together': {('user', 'task')},
            },
        ),
    ]
